#!/bin/bash -x

# Copyright 2015
#
# This file is part of FIWARE project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For those usages not covered by the Apache version 2.0 License please
# contact with opensource@tid.es
#
# Autor: Jose Ignacio Carretero Guarde.
#


[ -z $1 ] && exit 1

id=$1
#unset OS_TENANT_ID
#unset OS_TENANT_NAME
#export OS_REGION_NAME=
#export OS_USERNAME=
#export OS_PASSWORD=
#export OS_AUTH_URL=
#export OS_TENANT_NAME=

a=(`nova show $id | grep -v "+--*+--*+$" |sed 's.|..g' | awk '$1=="OS-EXT-SRV-ATTR:hypervisor_hostname" || $1=="id" {print $2}'`)
hn=${a[0]}
ip=`awk "/$hn\$/ {print \\$1}" /etc/hosts`

(virt-viewer -c qemu+ssh://root@$ip/system ${a[1]} & )
